class BNStatusBar : DoomStatusBar
{
	override void Init()
	{
		Super.Init();
	}

	override void Draw (int state, double TicFrac)
	{
		Super.Draw(state, TicFrac);

        if (NetNaviPlayer(CPlayer.mo)) 
        { 
            if (state == HUD_StatusBar)
		    {
			    BeginStatusBar();
			    DrawEmotionWindowStatus();
		    }
		    else if (state == HUD_Fullscreen)
		    {
			    BeginHUD();
			    DrawEmotionWindowFullscreen();
		    }
        }
	}

    protected void DrawEmotionWindowFullscreen () 
    {
        let player = NetNaviPlayer(CPlayer.mo);
        DrawImage("EMWIN"..player.curEmotion, (43, 32), DI_SCREEN_LEFT_TOP, 1., (-1, -1), (2, 2));
        DrawImage(player.EmotionFace..player.curEmotion, (43, 32), DI_SCREEN_LEFT_TOP, 1., (-1, -1), (2, 2));
    }

    protected void DrawEmotionWindowStatus () 
    {
        let player = NetNaviPlayer(CPlayer.mo);
        DrawImage("EMWIN"..player.curEmotion, (44, 171), DI_ITEM_OFFSETS);
        DrawImage(player.EmotionFace..player.curEmotion, (44, 171), DI_ITEM_OFFSETS);
    }
}