class MegaManPlayer : PlayerPawn
{
	Default
	{
		+NOBLOOD
		Speed 1;
		Health 100;
		Radius 16;
		Height 42;
		Mass 100;
		PainChance 256;
		Player.DisplayName "MegaMan";
		Player.StartItem "MegaBuster";
		Player.WeaponSlot 1, "MegaBuster";
		
		Player.ColorRange 112, 127;
		Player.Colorset 0, "Green",			0x70, 0x7F,  0x72;
		Player.Colorset 1, "Gray",			0x60, 0x6F,  0x62;
		Player.Colorset 2, "Brown",			0x40, 0x4F,  0x42;
		Player.Colorset 3, "Red",			0x20, 0x2F,  0x22;
		// Doom Legacy additions
		Player.Colorset 4, "Light Gray",	0x58, 0x67,  0x5A;
		Player.Colorset 5, "Light Brown",	0x38, 0x47,  0x3A;
		Player.Colorset 6, "Light Red",		0xB0, 0xBF,  0xB2;
		Player.Colorset 7, "Light Blue",	0xC0, 0xCF,  0xC2;
	}

	States
	{
		Spawn:
			BMEG A -1;
			Loop;
		See:
			BMEG BCDEFG 4;
			Loop;
		Missile:
			BMEG H 2;
			BMEG IJ 2 Bright;
			BMEG H 1;
			Goto Spawn;
		Pain:
			BMEG K 3 Bright;
			BMEG L 3 A_Pain;
			BMEG M 3;
			Goto Spawn;
		Death:
			BMEG N 7;
			BMEG O 7 A_NoBlocking;
			BMEG P 2 Bright;
			BMEG O 2;
			BMEG P 2 Bright;
			BMEG O 2;
			BMEG P 2 Bright;
			BMEG O 30 A_SpawnItem("BN6DeathEffect", 0, 27, 0); // I had to make this an object instead of an overlay because overlays just... weren't working.
			BMEG P 10 Bright A_PlayerScream;
			BMEG P 3 Bright A_SetTranslucent(0.90);
			BMEG P 3 Bright A_SetTranslucent(0.80);
			BMEG P 3 Bright A_SetTranslucent(0.70);
			BMEG P 3 Bright A_SetTranslucent(0.60);
			BMEG P 3 Bright A_SetTranslucent(0.50);
			BMEG P 3 Bright A_SetTranslucent(0.40);
			BMEG P 3 Bright A_SetTranslucent(0.30);
			BMEG P 3 Bright A_SetTranslucent(0.20);
			BMEG P 3 Bright A_SetTranslucent(0.10);
			BMEG P 3 Bright A_SetTranslucent(0.00);
			TNT1 A -1;
			Stop;
	}
}

class BN6DeathEffect : Actor
{
	Default
	{
		Mass 0;
		Gravity 0;
		+NOBLOCKMAP
		+NOGRAVITY
		+DONTFALL
	}
	States
	{
		Spawn:
			BNDE ABCDEFGHIJK 1 Bright;
			BNDE LMNOPQRSTUV 1 Bright;
			Stop;
	}
}