class NetNaviPlayer : PlayerPawn
{
	Default
	{
		Speed 1;
		Health 100;
		Radius 16;
		Height 42;
		Mass 100;
		PainChance 256;
		Player.DisplayName "MegaMan";
		Player.StartItem "Buster";
		Player.WeaponSlot 1, "Buster";
		
		Player.ColorRange 112, 127;
		Player.Colorset 0, "Green",			0x70, 0x7F,  0x72;
		Player.Colorset 1, "Gray",			0x60, 0x6F,  0x62;
		Player.Colorset 2, "Brown",			0x40, 0x4F,  0x42;
		Player.Colorset 3, "Red",			0x20, 0x2F,  0x22;
		// Doom Legacy additions
		Player.Colorset 4, "Light Gray",	0x58, 0x67,  0x5A;
		Player.Colorset 5, "Light Brown",	0x38, 0x47,  0x3A;
		Player.Colorset 6, "Light Red",		0xB0, 0xBF,  0xB2;
		Player.Colorset 7, "Light Blue",	0xC0, 0xCF,  0xC2;
	}

	States
	{
	Spawn:
		PLAY A -1;
		Loop;
	See:
		PLAY BCDEFG 4;
		Loop;
	Missile:
		PLAY H 4;
		PLAY IJ 4 Bright;
		PLAY H 4;
		Goto Spawn;
	Pain:
		PLAY K 2;
		PLAY L 2 A_Pain;
		PLAY K 2;
		PLAY L 2;
		PLAY K 2;
		PLAY L 2;
		Goto Spawn;
	Death:
		PLAY M 7 A_PlayerScream;
		PLAY N 7 A_NoBlocking;
		PLAY O 2;
		PLAY N 2;
		PLAY O 2;
		PLAY N 2;
		PLAY O 10;
		PLAY O 3 A_SetTranslucent(0.90);
		PLAY O 3 A_SetTranslucent(0.80);
		PLAY O 3 A_SetTranslucent(0.70);
		PLAY O 3 A_SetTranslucent(0.60);
		PLAY O 3 A_SetTranslucent(0.50);
		PLAY O 3 A_SetTranslucent(0.40);
		PLAY O 3 A_SetTranslucent(0.30);
		PLAY O 3 A_SetTranslucent(0.20);
		PLAY O 3 A_SetTranslucent(0.10);
		PLAY O 3 A_SetTranslucent(0.00);
		TNT1 A -1;
		Stop;
	}
}