extend class BusterBase {
	States {
		AirShotFire:
			BNAS BB 1 A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
			BNAS BB 1 A_OverlayOffset(OverlayID(), -2, -2, WOF_ADD);
			BNAS B 4;
			Stop;
		AirShotArm:
			TNT1 A 0 {
				A_Overlay(5,"ChargeSoundFunction"); //Starts charge sound.
				A_Overlay(-1, "ChargeEffectFunction"); // starts charge effect
			}
			BNAR AA 1 A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
			BNAR AA 1 A_OverlayOffset(OverlayID(), -2, -2, WOF_ADD);
			BNAR A 4;
			TNT1 A 0 { return ResolveState("Ready"); }
	}
}