extend class BusterBase {
	States {
		SwordBlade:
			SWSL AB 2 Bright;
			TNT1 A 0 A_StartSound("weapons/sword");
			SWSL CDEE 2 Bright;
			Stop;
		SwordSwing:	// He-hey, now I can use this for a generic arm type.
			TNT1 A 0 {
				A_Overlay(5,"ChargeSoundFunction"); //Starts charge sound.
				A_Overlay(-1, "ChargeEffectFunction"); // starts charge effect
			}
			NSRD ABCDEE 2;
			Goto Select;
	}
}