extend class BusterBase {
	States {
		SwordBlade:
			SWSL AB 2 Bright;
			TNT1 A 0 A_SpawnItemEx("SwordSlash", -8, -32, 24, 0, 0, 0, -90);	// Now it's a projectile, so it can be a small AoE thing.
			SWSL CDE 2 Bright;
			Stop;
		SwordSwing:	// He-hey, now I can use this for a generic arm type.
			TNT1 A 0 {
				A_Overlay(5,"ChargeSoundFunction"); //Starts charge sound.
				A_Overlay(-1, "ChargeEffectFunction"); // starts charge effect
			}
			NSRD ABCDE 2;
			Goto Select;
	}
}