extend class BusterBase {
	States {
		Chip.Vulcan1:
			BNVL A 1 { // 1
				A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
				A_FireProjectile("Vulcan1");
				A_Overlay(-3, "Flash");	// Flash layer
				A_OverlayRotate(-3, -15);
				A_OverlayOffset(-3, 20, -8);
				A_StartSound("weapons/gun");
			}
			BNVL B 1 A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
			BNVL CD 1 A_OverlayOffset(OverlayID(), -2, -2, WOF_ADD);
			BNVL A 1 { // 2
				A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
				A_FireProjectile("Vulcan1");
				A_Overlay(-3, "Flash");	// Flash layer
				A_OverlayRotate(-3, -15);
				A_OverlayOffset(-3, 20, -8);
				A_StartSound("weapons/gun");
			}
			BNVL B 1 A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
			BNVL CD 1 A_OverlayOffset(OverlayID(), -2, -2, WOF_ADD);
			BNVL A 1 { // 3
				A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
				A_FireProjectile("Vulcan1");
				A_Overlay(-3, "Flash");	// Flash layer
				A_OverlayRotate(-3, -15);
				A_OverlayOffset(-3, 20, -8);
				A_StartSound("weapons/gun");
			}
			BNVL B 1 A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
			BNVL CD 1 A_OverlayOffset(OverlayID(), -2, -2, WOF_ADD);
			TNT1 A 0 { return ResolveState("Ready"); }
		Chip.Vulcan2:
			BNVL A 1 { // 1
				A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
				A_FireProjectile("Vulcan2");
				A_Overlay(-3, "Flash");	// Flash layer
				A_OverlayRotate(-3, -15);
				A_OverlayOffset(-3, 20, -8);
				A_StartSound("weapons/gun");
			}
			BNVL B 1 A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
			BNVL CD 1 A_OverlayOffset(OverlayID(), -2, -2, WOF_ADD);
			BNVL A 1 { // 2
				A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
				A_FireProjectile("Vulcan2");
				A_Overlay(-3, "Flash");	// Flash layer
				A_OverlayRotate(-3, -15);
				A_OverlayOffset(-3, 20, -8);
				A_StartSound("weapons/gun");
			}
			BNVL B 1 A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
			BNVL CD 1 A_OverlayOffset(OverlayID(), -2, -2, WOF_ADD);
			BNVL A 1 { // 3
				A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
				A_FireProjectile("Vulcan2");
				A_Overlay(-3, "Flash");	// Flash layer
				A_OverlayRotate(-3, -15);
				A_OverlayOffset(-3, 20, -8);
				A_StartSound("weapons/gun");
			}
			BNVL B 1 A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
			BNVL CD 1 A_OverlayOffset(OverlayID(), -2, -2, WOF_ADD);
			BNVL A 1 { // 4
				A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
				A_FireProjectile("Vulcan2");
				A_Overlay(-3, "Flash");	// Flash layer
				A_OverlayRotate(-3, -15);
				A_OverlayOffset(-3, 20, -8);
				A_StartSound("weapons/gun");
			}
			BNVL B 1 A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
			BNVL CD 1 A_OverlayOffset(OverlayID(), -2, -2, WOF_ADD);
			TNT1 A 0 { return ResolveState("Ready"); }
		Chip.Vulcan3:
			BNVL A 1 { // 1
				A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
				A_FireProjectile("Vulcan3");
				A_Overlay(-3, "Flash");	// Flash layer
				A_OverlayRotate(-3, -15);
				A_OverlayOffset(-3, 20, -8);
				A_StartSound("weapons/gun");
			}
			BNVL B 1 A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
			BNVL CD 1 A_OverlayOffset(OverlayID(), -2, -2, WOF_ADD);
			BNVL A 1 { // 2
				A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
				A_FireProjectile("Vulcan3");
				A_Overlay(-3, "Flash");	// Flash layer
				A_OverlayRotate(-3, -15);
				A_OverlayOffset(-3, 20, -8);
				A_StartSound("weapons/gun");
			}
			BNVL B 1 A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
			BNVL CD 1 A_OverlayOffset(OverlayID(), -2, -2, WOF_ADD);
			BNVL A 1 { // 3
				A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
				A_FireProjectile("Vulcan3");
				A_Overlay(-3, "Flash");	// Flash layer
				A_OverlayRotate(-3, -15);
				A_OverlayOffset(-3, 20, -8);
				A_StartSound("weapons/gun");
			}
			BNVL B 1 A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
			BNVL CD 1 A_OverlayOffset(OverlayID(), -2, -2, WOF_ADD);
			BNVL A 1 { // 4
				A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
				A_FireProjectile("Vulcan3");
				A_Overlay(-3, "Flash");	// Flash layer
				A_OverlayRotate(-3, -15);
				A_OverlayOffset(-3, 20, -8);
				A_StartSound("weapons/gun");
			}
			BNVL B 1 A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
			BNVL CD 1 A_OverlayOffset(OverlayID(), -2, -2, WOF_ADD);
			BNVL A 1 { // 5
				A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
				A_FireProjectile("Vulcan3");
				A_Overlay(-3, "Flash");	// Flash layer
				A_OverlayRotate(-3, -15);
				A_OverlayOffset(-3, 20, -8);
				A_StartSound("weapons/gun");
			}
			BNVL B 1 A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
			BNVL CD 1 A_OverlayOffset(OverlayID(), -2, -2, WOF_ADD);
			TNT1 A 0 { return ResolveState("Ready"); }
		Chip.SuprVulc:
			TNT1 A 0 A_OverlayTranslation(OverlayID(), "");
			BNVL E 1 { // 1
				A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
				A_FireProjectile("Vulcan3");
				A_Overlay(-3, "Flash");	// Flash layer
				A_OverlayRotate(-3, -15);
				A_OverlayOffset(-3, 20, -8);
				A_StartSound("weapons/gun");
			}
			BNVL F 1 A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
			BNVL GH 1 A_OverlayOffset(OverlayID(), -2, -2, WOF_ADD);
			BNVL E 1 { // 2
				A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
				A_FireProjectile("Vulcan3");
				A_Overlay(-3, "Flash");	// Flash layer
				A_OverlayRotate(-3, -15);
				A_OverlayOffset(-3, 20, -8);
				A_StartSound("weapons/gun");
			}
			BNVL F 1 A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
			BNVL GH 1 A_OverlayOffset(OverlayID(), -2, -2, WOF_ADD);
			BNVL E 1 { // 3
				A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
				A_FireProjectile("Vulcan3");
				A_Overlay(-3, "Flash");	// Flash layer
				A_OverlayRotate(-3, -15);
				A_OverlayOffset(-3, 20, -8);
				A_StartSound("weapons/gun");
			}
			BNVL F 1 A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
			BNVL GH 1 A_OverlayOffset(OverlayID(), -2, -2, WOF_ADD);
			BNVL E 1 { // 4
				A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
				A_FireProjectile("Vulcan3");
				A_Overlay(-3, "Flash");	// Flash layer
				A_OverlayRotate(-3, -15);
				A_OverlayOffset(-3, 20, -8);
				A_StartSound("weapons/gun");
			}
			BNVL F 1 A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
			BNVL GH 1 A_OverlayOffset(OverlayID(), -2, -2, WOF_ADD);
			BNVL E 1 { // 5
				A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
				A_FireProjectile("Vulcan3");
				A_Overlay(-3, "Flash");	// Flash layer
				A_OverlayRotate(-3, -15);
				A_OverlayOffset(-3, 20, -8);
				A_StartSound("weapons/gun");
			}
			BNVL F 1 A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
			BNVL GH 1 A_OverlayOffset(OverlayID(), -2, -2, WOF_ADD);
			BNVL E 1 { // 6
				A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
				A_FireProjectile("Vulcan3");
				A_Overlay(-3, "Flash");	// Flash layer
				A_OverlayRotate(-3, -15);
				A_OverlayOffset(-3, 20, -8);
				A_StartSound("weapons/gun");
			}
			BNVL F 1 A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
			BNVL GH 1 A_OverlayOffset(OverlayID(), -2, -2, WOF_ADD);
			BNVL E 1 { // 7
				A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
				A_FireProjectile("Vulcan3");
				A_Overlay(-3, "Flash");	// Flash layer
				A_OverlayRotate(-3, -15);
				A_OverlayOffset(-3, 20, -8);
				A_StartSound("weapons/gun");
			}
			BNVL F 1 A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
			BNVL GH 1 A_OverlayOffset(OverlayID(), -2, -2, WOF_ADD);
			BNVL E 1 { // 8
				A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
				A_FireProjectile("Vulcan3");
				A_Overlay(-3, "Flash");	// Flash layer
				A_OverlayRotate(-3, -15);
				A_OverlayOffset(-3, 20, -8);
				A_StartSound("weapons/gun");
			}
			BNVL F 1 A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
			BNVL GH 1 A_OverlayOffset(OverlayID(), -2, -2, WOF_ADD);
			BNVL E 1 { // 9
				A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
				A_FireProjectile("Vulcan3");
				A_Overlay(-3, "Flash");	// Flash layer
				A_OverlayRotate(-3, -15);
				A_OverlayOffset(-3, 20, -8);
				A_StartSound("weapons/gun");
			}
			BNVL F 1 A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
			BNVL GH 1 A_OverlayOffset(OverlayID(), -2, -2, WOF_ADD);
			BNVL E 1 { // 10
				A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
				A_FireProjectile("Vulcan3");
				A_Overlay(-3, "Flash");	// Flash layer
				A_OverlayRotate(-3, -15);
				A_OverlayOffset(-3, 20, -8);
				A_StartSound("weapons/gun");
			}
			BNVL F 1 A_OverlayOffset(OverlayID(), 2, 2, WOF_ADD);
			BNVL GH 1 A_OverlayOffset(OverlayID(), -2, -2, WOF_ADD);
			TNT1 A 0 { return ResolveState("Ready"); }
	}
}

class Vulcan1 : UnchargedBusterTracer
{
	Default
	{
		DamageFunction 10;
		Obituary "%o was perforated by %k's Vulcan.";
	}
	States
	{
		Spawn:
			BNTR F 1 Bright {LineAttack(angle, PLAYERMISSILERANGE, pitch, 0, 'Normal', "NullPuff", LAF_TARGETISSOURCE);}
			Loop;
	}
}
class Vulcan2 : Vulcan1
{
	Default
	{
		DamageFunction 15;
	}
}
class Vulcan3 : Vulcan1
{
	Default
	{
		DamageFunction 20;
	}
}