class RockCube : ExplosiveBarrel
{
	Default
	{
		PainChance 256;
		Radius 24;
		Height 40;
		Health 200;
		Damage 200;
		+DONTTHRUST
		-MISSILE
		Obituary "%o got a RockCube shoved in %p face by %k.";
		DeathSound "weapons/break_object";
	}
	States
	{
		Spawn:
			BNOB A 6000 A_Die;
			Stop;
		Pain.Wind:
			BNOB A 1 {
				bDontThrust = false;
				bMissile = true;
				bStepMissile = true;
			}
			BNOB A 0 A_FaceTarget;
			Goto Moving;
		Moving:
			BNOB A 1 A_ChangeVelocity(-20, 0, 0, CVF_RELATIVE|CVF_REPLACE);
			Loop;
		Death:
			TNT1 A 1 {
				A_SpawnItemEx("RockCubeHalf1", 0, 0, 0, frandom(0,5), frandom(0,5), 7.5);
				A_SpawnItemEx("RockCubeHalf2", 0, 0, 0, frandom(-5,0), frandom(-5,0), 7.5);
			}
			Stop;
	}
}

class MetalCube : RockCube
{
	Default
	{
		Health 400;
		Damage 400;
		Obituary "%o got a MetlCube shoved in %p face by %k.";
	}
	States
	{
		Spawn:
			BNOB D 6000 A_Die;
			Stop;
		Pain.Wind:
			BNOB D 1 {
				bDontThrust = false;
				bMissile = true;
				bStepMissile = true;
			}
			BNOB D 0 A_FaceTarget;
			Goto Moving;
		Moving:
			BNOB D 1 A_ChangeVelocity(-20, 0, 0, CVF_RELATIVE|CVF_REPLACE);
			Loop;
		Death:
			TNT1 A 1 {
				A_SpawnItemEx("MetalCubeHalf1", 0, 0, 0, frandom(0,5), frandom(0,5), 7.5);
				A_SpawnItemEx("MetalCubeHalf2", 0, 0, 0, frandom(-5,0), frandom(-5,0), 7.5);
			}
			Stop;
	}
}

class RockCubeHalf1 : Actor
{
	Default
	{
		Projectile;
		+NOBLOCKMAP
		-NOGRAVITY
		Gravity 1;
		Mass 50;
		BounceType "Heretic";
		BounceCount 1;
	}
	States
	{
		Spawn:
			BNOB B 1;
			Loop;
		Death:
			BNOB B 1;
			TNT1 A 1;
			BNOB B 1;
			TNT1 A 1;
			BNOB B 1;
			TNT1 A 1;
			BNOB B 1;
			TNT1 A 1;
			Stop;
	}
}

class RockCubeHalf2 : RockCubeHalf1
{
	States
	{
		Spawn:
			BNOB C 1;
			Loop;
		Death:
			BNOB C 1;
			TNT1 A 1;
			BNOB C 1;
			TNT1 A 1;
			BNOB C 1;
			TNT1 A 1;
			BNOB C 1;
			TNT1 A 1;
			Stop;
	}
}

class MetalCubeHalf1 : RockCubeHalf1
{
	States
	{
		Spawn:
			BNOB E 1;
			Loop;
		Death:
			BNOB E 1;
			TNT1 A 1;
			BNOB E 1;
			TNT1 A 1;
			BNOB E 1;
			TNT1 A 1;
			BNOB E 1;
			TNT1 A 1;
			Stop;
	}
}

class MetalCubeHalf2 : RockCubeHalf1
{
	States
	{
		Spawn:
			BNOB F 1;
			Loop;
		Death:
			BNOB F 1;
			TNT1 A 1;
			BNOB F 1;
			TNT1 A 1;
			BNOB F 1;
			TNT1 A 1;
			BNOB F 1;
			TNT1 A 1;
			Stop;
	}
}