class RockCube : ExplosiveBarrel
{
	Default
	{
		+DONTTHRUST
		Obituary "%o got a RockCube shoved in %p face by %o.";
	}
	States
	{
		Spawn:
			BNOB A 1;
			Loop;
		Death:
			TNT1 A 0 {
				A_SpawnItemEx("RockCubeHalf1", 0, 0, 0, 0, 0, 5, frandom(0,5));
				A_SpawnItemEx("RockCubeHalf2", 0, 0, 0, 0, 0, 5, frandom(0,-5));
			}
			Stop;
	}
}

class RockCubeHalf1 : Actor
{
	Default
	{
		+NOBLOCKMAP
		Gravity 0.50;
		BounceType "Heretic";
		BounceCount 1;
	}
	States
	{
		Spawn:
			BNOB B 1;
			Loop;
		Death:
			TNT1 A 0;
			Stop;
	}
}

class RockCubeHalf2 : RockCubeHalf1
{
	States
	{
		Spawn:
			BNOB C 1;
			Loop;
	}
}