class PrimaryCharge : Inventory
{
	Default
	{
		Inventory.MaxAmount 100;
	}
}

class ChargingSoundPlayed : Inventory
{
	Default
	{
		Inventory.MaxAmount 1;
	}
}

class ChargedSoundPlayed : Inventory
{
	Default
	{
		Inventory.MaxAmount 1;
	}
}

class Buster : Weapon
{
	Default
	{
		Weapon.SelectionOrder 3700;
		Obituary "Test obituary: %o killed %k.";
		+WEAPON.WIMPY_WEAPON;
		Inventory.Pickupmessage "You shouldn't be seeing this.";
		Tag "Buster";
	}
	States
	{
		Ready:
			MBUS A 1 A_WeaponReady;
			Loop;
		Deselect:
			MBUS A 1 A_Lower;
			Loop;
		Select:
			MBUS A 1 A_Raise;
			Loop;
		Fire:
			MBUS A 2 {
				A_TakeInventory("PrimaryCharge", 100);
				A_TakeInventory("ChargingSoundPlayed", 1);
				A_TakeInventory("ChargedSoundPlayed", 1);
				A_ReFire();
			}
			Goto Ready;
		Hold:
			MBUS A 2 {
				A_JumpIfInTargetInventory("PrimaryCharge", 100, "PlayChargedSound");
				A_JumpIfInTargetInventory("ChargingSoundPlayed", 1, "AddCharge");
				A_Refire("PlayChargingSound");
			}
			Goto FireNormalShot;
		FireNormalShot:
			MBUS A 2;
			MBUS B 6 Bright {
				A_FireBullets(2.85, 2.85, 1, 3, "UnchargedBusterPuff");
				A_PlaySound("weapons/buster/pew", CHAN_WEAPON);
			}
			MBUS C 4;
			MBUS D 4;
			Goto Ready;
		AltFire:
			MBUS A 2;
			MBUS B 6 Bright {
				A_FireBullets(2.85, 2.85, 1, 3, "UnchargedBusterPuff");
				A_PlaySound("weapons/buster/pew", CHAN_WEAPON);
			}
			MBUS C 4;
			MBUS D 4 A_ReFire;
			Goto Ready;
		Spawn:
			SHTG A -1;
			Stop;
		PlayChargingSound:
			MBUS A 0 {
				A_GiveInventory("ChargingSoundPlayed", 1);
				A_PlaySound("weapons/buster/charging", CHAN_WEAPON);
			}
		AddCharge:
			MBUS A 0 A_GiveInventory("PrimaryCharge", 1);
			Goto Hold;
		PlayChargedSound:
			MBUS A 0 {
				A_JumpIfInTargetInventory("ChargedSoundPlayed", 1, "Hold");
				A_GiveInventory("ChargedSoundPlayed", 1);
				A_PlaySound("weapons/buster/charged", CHAN_WEAPON);
			}
			Goto Hold;
	}
}

class BusterPuffBase : Actor
{
	Default
	{
		SeeSound "weapons/hit";
		+NOBLOCKMAP
		+NOGRAVITY
		+ALLOWPARTICLES
		+PUFFONACTORS
	}
	States
	{
		Spawn:
			PUFF ABCD 4 Bright;
			Stop;
	}
}

class UnchargedBusterPuff : BusterPuffBase
{
	Default
	{
		Obituary "%o was tickled to death by %k's uncharged buster shots.";
	}
	States
	{
		Spawn:
			BNP0 ABCD 1 Bright;
			Stop;
	}
}

class ChargedBusterPuff : BusterPuffBase
{
	Default
	{
		Obituary "%o was blasted by %k's charge shot.";
	}
	States
	{
		Spawn:
			BNP1 AB 1 Bright;
			BNP1 CDE 2 Bright;
			BNP1 F 3 Bright;
			Stop;
	}
}